In [1]:
import numpy as np


In [28]:
kanto = np.array([23,24,25])
weight = np.array([3,4,5])

In [20]:
(kanto * weight).sum()

290

In [21]:
np.dot(kanto, weight)

290

In [29]:
kanto.shape

(3,)

In [73]:
ben = np.array([[2,3,4,5], 
                [5,6,7,8], 
                [8,7,6,7], ])
ken = np.array([2,3,2,3])

In [66]:
ben.shape

(4, 4)

In [72]:
ben @ ken 

array([36, 66, 70])

In [62]:
(ben * ken)

array([[ 4,  9,  8, 15],
       [10, 18, 14, 24],
       [16, 21, 12, 21]])

In [75]:
import urllib.request

In [ ]:
url = 'https://filesamples.com/samples/document/csv/sample4.csv'

In [86]:
urllib.request.urlretrieve(url, 'sampledata.txt')


('sampledata.txt', <http.client.HTTPMessage at 0x1efbefd49d0>)

In [88]:
sampledata = np.genfromtxt('sampledata.txt', delimiter=',', skip_header=1)

In [89]:
sampledata

array([[           nan, 1.36000000e+02, 1.36335495e+02, ...,
        1.36279999e+02, 1.36279999e+02, 1.90640000e+07],
       [           nan, 1.36249496e+02, 1.36537994e+02, ...,
        1.36028503e+02, 1.36028503e+02, 1.65280000e+07],
       [           nan, 1.36028503e+02, 1.36949997e+02, ...,
        1.36940002e+02, 1.36940002e+02, 1.18660000e+07],
       ...,
       [           nan, 1.15529999e+02, 1.17120003e+02, ...,
        1.15480003e+02, 1.15480003e+02, 2.28562000e+07],
       [           nan, 1.14430000e+02, 1.17080002e+02, ...,
        1.15900002e+02, 1.15900002e+02, 1.79110000e+07],
       [           nan, 1.16339996e+02, 1.19410004e+02, ...,
        1.18779999e+02, 1.18779999e+02, 2.44389350e+07]])

In [92]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '