In [56]:
import numpy as np
bee = np.array([[1,2,3], 
                [4,5,6],])
cee = np.array([2,2,3])
cee * bee



array([[ 2,  4,  9],
       [ 8, 10, 18]])

In [60]:
np.sum(bee, axis=0)

array([5, 7, 9])

In [85]:
float(bee[0,2])

3.0

In [16]:
joe = [2,3,4,5,6]
joe[4:]

[6]

In [49]:
bee.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [4],
       [4],
       [4]])

In [41]:
import os

In [52]:
os.getcwd()

'c:\\Users\\Acer\\OneDrive\\Desktop\\intro to python\\lessons'

In [69]:
kwekuuu = 'C:\\Users\Acer\OneDrive\Desktop\data analysis'

In [70]:
os.listdir(kwekuuu)

['data analysis career path.docx',
 'Excel tips.docx',
 'EXCEL WORK.xlsx',
 'MY DASHBOARD.xlsx',
 'python notes.docx',
 'Screenshot 2022-07-31 230646.png',
 'Script.sql',
 'SQL.docx',
 'tableau tipss.docx',
 '~$thon notes.docx']

In [83]:
os.makedirs('.\wdata')

In [80]:
os.makedirs('.\wata', exist_ok=True)

In [25]:
fileA = open('.\wdata\sampledata.txt', mode='w')

In [26]:
fileA.write('{},{},{},{},{}\n'.format(joe[0],joe[1],joe[2],joe[3],joe[4]))

10

In [28]:
fileA.close()

In [32]:
fileA = open('.\wdata\sampledata.txt', mode='r')

In [34]:
content = fileA.read()

In [37]:
print(content)

In [39]:
fileA.close()