In [1]:
import numpy as np
import pandas as pd


In [2]:
scores = [23,24,25,26,27,28]
type(scores)

list

In [3]:
new = np.array(scores)
type(new)

numpy.ndarray

In [4]:
new[0:5]

array([23, 24, 25, 26, 27])

In [5]:
new[0:5:2]

array([23, 25, 27])

In [6]:
path = "C:\\Users\Acer\Downloads\practice data.txt"

In [7]:
#here we read a text file containing 3 columns(amount, units and totl cost).
sampledata = np.genfromtxt(path, dtype=int, skip_header=1, delimiter='') 
sampledata

array([[ 1057,    54,   632],
       [ 1281,    75,   878],
       [ 1932,   369,  4317],
       [ 2415,   255,  2984],
       [ 3472,    96,  1123],
       [ 3976,    72,   842],
       [ 4606,    63,   737],
       [ 4991,    12,   140],
       [ 5586,   525,  6143],
       [ 6608,   225,  2633],
       [ 7259,   276,  3229],
       [   42,   150,  2174],
       [  560,    81,  1174],
       [ 1526,   240,  3478],
       [ 1526,   105,  1521],
       [ 1624,   114,  1652],
       [ 1638,    63,   913],
       [ 2275,   447,  6477],
       [ 3402,   366,  5303],
       [ 3598,    81,  1174],
       [ 4781,   123,  1782],
       [ 6118,   174,  2521],
       [ 6454,    54,   782],
       [ 6755,   252,  3651],
       [ 7021,   183,  2652],
       [ 9051,    57,   826],
       [10129,   312,  4521],
       [  623,    51,   253],
       [ 1638,    48,   239],
       [ 2793,   114,   567],
       [ 2989,     3,    15],
       [ 3920,   306,  1521],
       [ 4018,   171,   850],
       [ 4

In [8]:
sampledata.shape

(300, 3)

In [9]:
sampledata[0:150,0:3:2]

array([[ 1057,   632],
       [ 1281,   878],
       [ 1932,  4317],
       [ 2415,  2984],
       [ 3472,  1123],
       [ 3976,   842],
       [ 4606,   737],
       [ 4991,   140],
       [ 5586,  6143],
       [ 6608,  2633],
       [ 7259,  3229],
       [   42,  2174],
       [  560,  1174],
       [ 1526,  3478],
       [ 1526,  1521],
       [ 1624,  1652],
       [ 1638,   913],
       [ 2275,  6477],
       [ 3402,  5303],
       [ 3598,  1174],
       [ 4781,  1782],
       [ 6118,  2521],
       [ 6454,   782],
       [ 6755,  3651],
       [ 7021,  2652],
       [ 9051,   826],
       [10129,  4521],
       [  623,   253],
       [ 1638,   239],
       [ 2793,   567],
       [ 2989,    15],
       [ 3920,  1521],
       [ 4018,   850],
       [ 4137,   298],
       [ 6398,   507],
       [ 8862,   939],
       [  238,   138],
       [  553,   115],
       [  609,   756],
       [  861,  1490],
       [ 1281,   138],
       [ 1771,  1559],
       [ 1925,  1467],
       [ 28

In [10]:
sampledata[0:1,0:1] = 1020

In [11]:
sampledata[0:1,0:1]

array([[1020]])

In [12]:
sampledata

array([[ 1020,    54,   632],
       [ 1281,    75,   878],
       [ 1932,   369,  4317],
       [ 2415,   255,  2984],
       [ 3472,    96,  1123],
       [ 3976,    72,   842],
       [ 4606,    63,   737],
       [ 4991,    12,   140],
       [ 5586,   525,  6143],
       [ 6608,   225,  2633],
       [ 7259,   276,  3229],
       [   42,   150,  2174],
       [  560,    81,  1174],
       [ 1526,   240,  3478],
       [ 1526,   105,  1521],
       [ 1624,   114,  1652],
       [ 1638,    63,   913],
       [ 2275,   447,  6477],
       [ 3402,   366,  5303],
       [ 3598,    81,  1174],
       [ 4781,   123,  1782],
       [ 6118,   174,  2521],
       [ 6454,    54,   782],
       [ 6755,   252,  3651],
       [ 7021,   183,  2652],
       [ 9051,    57,   826],
       [10129,   312,  4521],
       [  623,    51,   253],
       [ 1638,    48,   239],
       [ 2793,   114,   567],
       [ 2989,     3,    15],
       [ 3920,   306,  1521],
       [ 4018,   171,   850],
       [ 4

In [13]:
amount = sampledata[:,0]
amount.shape

(300,)

In [14]:
amount

array([ 1020,  1281,  1932,  2415,  3472,  3976,  4606,  4991,  5586,
        6608,  7259,    42,   560,  1526,  1526,  1624,  1638,  2275,
        3402,  3598,  4781,  6118,  6454,  6755,  7021,  9051, 10129,
         623,  1638,  2793,  2989,  3920,  4018,  4137,  6398,  8862,
         238,   553,   609,   861,  1281,  1771,  1925,  2870,  4018,
        4585,  5355,  5474,  7511,  7693,   168,   336,   490,   518,
        1568,  1890,  2205,  4053,  5012,  5817,  5915,  6279,  6853,
        6909,  8435,  9835,   217,   259,   525,   938,   959,  1302,
        2744,  3549,  6125,  6860, 10073,    98,    98,   609,  1561,
        2324,  2436,  2856,  3108,  4956,  4991,  5236,  5306,  6279,
        6748,  6818,  8008,  8841,   854,   973,  1652,  2919,  3059,
        3101,  3556,  3689,  5194,  5677,  6027,  6580,  7308,  7455,
       14329,   280,  2954,  3262,  3752,  5075,  6118,  6657,  6706,
        6734,  7777, 10304, 12348,   385,  1505,  1778,  2415,  2639,
        2646,  3808,

In [15]:
amount_reshape = amount.reshape(300,1)
amount_reshape

array([[ 1020],
       [ 1281],
       [ 1932],
       [ 2415],
       [ 3472],
       [ 3976],
       [ 4606],
       [ 4991],
       [ 5586],
       [ 6608],
       [ 7259],
       [   42],
       [  560],
       [ 1526],
       [ 1526],
       [ 1624],
       [ 1638],
       [ 2275],
       [ 3402],
       [ 3598],
       [ 4781],
       [ 6118],
       [ 6454],
       [ 6755],
       [ 7021],
       [ 9051],
       [10129],
       [  623],
       [ 1638],
       [ 2793],
       [ 2989],
       [ 3920],
       [ 4018],
       [ 4137],
       [ 6398],
       [ 8862],
       [  238],
       [  553],
       [  609],
       [  861],
       [ 1281],
       [ 1771],
       [ 1925],
       [ 2870],
       [ 4018],
       [ 4585],
       [ 5355],
       [ 5474],
       [ 7511],
       [ 7693],
       [  168],
       [  336],
       [  490],
       [  518],
       [ 1568],
       [ 1890],
       [ 2205],
       [ 4053],
       [ 5012],
       [ 5817],
       [ 5915],
       [ 6279],
       [

In [16]:
np.sort(amount_reshape, axis=0)

array([[    0],
       [   21],
       [   42],
       [   56],
       [   63],
       [   98],
       [   98],
       [  154],
       [  168],
       [  182],
       [  189],
       [  217],
       [  238],
       [  245],
       [  252],
       [  259],
       [  280],
       [  336],
       [  357],
       [  385],
       [  434],
       [  469],
       [  490],
       [  497],
       [  518],
       [  525],
       [  553],
       [  560],
       [  567],
       [  609],
       [  609],
       [  623],
       [  630],
       [  700],
       [  707],
       [  714],
       [  798],
       [  819],
       [  819],
       [  847],
       [  854],
       [  861],
       [  938],
       [  938],
       [  938],
       [  945],
       [  959],
       [  959],
       [  966],
       [  973],
       [ 1020],
       [ 1071],
       [ 1085],
       [ 1134],
       [ 1274],
       [ 1281],
       [ 1281],
       [ 1302],
       [ 1400],
       [ 1407],
       [ 1428],
       [ 1442],
       [

In [17]:
sorted_amount_asc = np.sort(amount)
sorted_amount_asc

array([    0,    21,    42,    56,    63,    98,    98,   154,   168,
         182,   189,   217,   238,   245,   252,   259,   280,   336,
         357,   385,   434,   469,   490,   497,   518,   525,   553,
         560,   567,   609,   609,   623,   630,   700,   707,   714,
         798,   819,   819,   847,   854,   861,   938,   938,   938,
         945,   959,   959,   966,   973,  1020,  1071,  1085,  1134,
        1274,  1281,  1281,  1302,  1400,  1407,  1428,  1442,  1463,
        1505,  1526,  1526,  1561,  1568,  1568,  1589,  1617,  1624,
        1638,  1638,  1652,  1652,  1701,  1771,  1778,  1785,  1890,
        1904,  1925,  1932,  1974,  1988,  2009,  2016,  2023,  2023,
        2100,  2114,  2114,  2135,  2142,  2149,  2205,  2205,  2212,
        2219,  2226,  2268,  2275,  2289,  2317,  2317,  2324,  2408,
        2415,  2415,  2429,  2436,  2464,  2471,  2478,  2541,  2541,
        2562,  2583,  2639,  2646,  2646,  2681,  2702,  2737,  2744,
        2779,  2793,

In [18]:
sorted_amount_desc = sorted_amount_asc[::-1]

In [19]:
sorted_amount_desc

array([16184, 15610, 14329, 13391, 12950, 12348, 11571, 11522, 11417,
       10311, 10304, 10129, 10073,  9926,  9835,  9772,  9709,  9660,
        9632,  9506,  9443,  9198,  9051,  9002,  8890,  8869,  8862,
        8841,  8813,  8463,  8435,  8211,  8155,  8008,  7847,  7833,
        7812,  7777,  7777,  7693,  7693,  7651,  7511,  7483,  7455,
        7322,  7308,  7280,  7273,  7259,  7189,  7021,  6986,  6909,
        6860,  6853,  6832,  6818,  6755,  6748,  6734,  6706,  6657,
        6657,  6608,  6580,  6454,  6433,  6398,  6391,  6370,  6314,
        6300,  6279,  6279,  6146,  6132,  6125,  6118,  6118,  6111,
        6048,  6027,  5915,  5817,  5775,  5677,  5670,  5586,  5551,
        5474,  5439,  5355,  5306,  5236,  5194,  5075,  5019,  5019,
        5012,  4991,  4991,  4970,  4956,  4949,  4935,  4858,  4802,
        4781,  4760,  4753,  4753,  4725,  4683,  4606,  4592,  4585,
        4487,  4487,  4480,  4438,  4424,  4417,  4326,  4319,  4305,
        4242,  4137,

In [20]:
#so now we can get to 10 values in the amount column :
sorted_amount_desc[0:10]

array([16184, 15610, 14329, 13391, 12950, 12348, 11571, 11522, 11417,
       10311])

In [21]:
sorted_amount_asc[0:10]

array([  0,  21,  42,  56,  63,  98,  98, 154, 168, 182])

In [22]:
#total amount values
amount.sum()

1240832

In [23]:
amount.max()

16184

In [24]:
np.min(amount)

0

In [25]:
amount.mean()

4136.106666666667

In [26]:
np.zeros((3,4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.full((3,4), 32)

array([[32, 32, 32, 32],
       [32, 32, 32, 32],
       [32, 32, 32, 32]])

In [29]:
np.random.randint(2,8,(3,4))

array([[5, 4, 2, 5],
       [3, 6, 2, 3],
       [3, 6, 5, 3]])

In [30]:
np.random.rand(2,8)

array([[0.02773039, 0.78542257, 0.88687362, 0.46294734, 0.77510302,
        0.00221545, 0.74763482, 0.91830319],
       [0.71881279, 0.47599442, 0.3896099 , 0.73626542, 0.7215984 ,
        0.78197831, 0.96594831, 0.45903536]])

In [31]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [32]:
b = np.array([2,3,2,3])
b

array([2, 3, 2, 3])

In [33]:
np.dot(a,b)

16

In [34]:
(a*b).sum()

16

In [35]:
a*b

array([0, 3, 4, 9])

In [36]:
bee = ([[2,3,4],
        [1,2,3]])
cee = np.full((3,3), 2)
cee

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [37]:
np.dot(bee, cee) #in a 2d array, dot product is same as matmul fxn

array([[18, 18, 18],
       [12, 12, 12]])

In [38]:
np.matmul(bee,cee)

array([[18, 18, 18],
       [12, 12, 12]])

In [39]:
bee @ cee

array([[18, 18, 18],
       [12, 12, 12]])

In [40]:
cee * bee

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [ ]:
cee

In [ ]:
dee = np.full((3,3), 3)
dee

In [ ]:
cee * dee

In [41]:
cee * 3

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [42]:
gee =np.array([2,3,4])

In [43]:
cee*gee

array([[4, 6, 8],
       [4, 6, 8],
       [4, 6, 8]])

In [59]:
bee = np.linspace(1,5,9)
bee

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [65]:
sampledata[0,0] == sampledata[0,1]

False

In [66]:
sampledata  #3 columns here reps amount, units and totl cost.

array([[ 1020,    54,   632],
       [ 1281,    75,   878],
       [ 1932,   369,  4317],
       [ 2415,   255,  2984],
       [ 3472,    96,  1123],
       [ 3976,    72,   842],
       [ 4606,    63,   737],
       [ 4991,    12,   140],
       [ 5586,   525,  6143],
       [ 6608,   225,  2633],
       [ 7259,   276,  3229],
       [   42,   150,  2174],
       [  560,    81,  1174],
       [ 1526,   240,  3478],
       [ 1526,   105,  1521],
       [ 1624,   114,  1652],
       [ 1638,    63,   913],
       [ 2275,   447,  6477],
       [ 3402,   366,  5303],
       [ 3598,    81,  1174],
       [ 4781,   123,  1782],
       [ 6118,   174,  2521],
       [ 6454,    54,   782],
       [ 6755,   252,  3651],
       [ 7021,   183,  2652],
       [ 9051,    57,   826],
       [10129,   312,  4521],
       [  623,    51,   253],
       [ 1638,    48,   239],
       [ 2793,   114,   567],
       [ 2989,     3,    15],
       [ 3920,   306,  1521],
       [ 4018,   171,   850],
       [ 4

In [72]:
#profit = amount * units
profit = sampledata[:,0] * sampledata[:,1]
profit

array([  55080,   96075,  712908,  615825,  333312,  286272,  290178,
         59892, 2932650, 1486800, 2003484,    6300,   45360,  366240,
        160230,  185136,  103194, 1016925, 1245132,  291438,  588063,
       1064532,  348516, 1702260, 1284843,  515907, 3160248,   31773,
         78624,  318402,    8967, 1199520,  687078,  248220,  652596,
       1674918,    4284,    8295,   60291,  167895,   23058,  361284,
        369600,  861000,  650916, 1100400, 1092420,  919632,  901320,
        161553,   14112,   48384,   41160,   38850,  221088,  368550,
        310905,   97272, 1052520,   69804,   17745, 1488123, 2549316,
        559629,  354270, 2035845,    7812,   53613,   25200,  343308,
        140973,  523404,   24696,   10647,  624750,  864360, 1208760,
         19992,   15582,   52983,   42147,  411348,  241164,  702576,
        167832,  847476,   44919,  267036,       0,  282555,  323904,
         40908, 3651648, 2678823,  263886,  157626,  168504,  131355,
         82593,  697

In [73]:
profit.sum()

191787453

In [74]:
profit.mean()

639291.51

In [78]:
#now we add profit col back to sampledata.
profit_col = profit.reshape(300,1)
profit_col

array([[  55080],
       [  96075],
       [ 712908],
       [ 615825],
       [ 333312],
       [ 286272],
       [ 290178],
       [  59892],
       [2932650],
       [1486800],
       [2003484],
       [   6300],
       [  45360],
       [ 366240],
       [ 160230],
       [ 185136],
       [ 103194],
       [1016925],
       [1245132],
       [ 291438],
       [ 588063],
       [1064532],
       [ 348516],
       [1702260],
       [1284843],
       [ 515907],
       [3160248],
       [  31773],
       [  78624],
       [ 318402],
       [   8967],
       [1199520],
       [ 687078],
       [ 248220],
       [ 652596],
       [1674918],
       [   4284],
       [   8295],
       [  60291],
       [ 167895],
       [  23058],
       [ 361284],
       [ 369600],
       [ 861000],
       [ 650916],
       [1100400],
       [1092420],
       [ 919632],
       [ 901320],
       [ 161553],
       [  14112],
       [  48384],
       [  41160],
       [  38850],
       [ 221088],
       [ 3

In [83]:
newdata = np.concatenate((sampledata, profit_col), axis=1)
newdata

array([[  1020,     54,    632,  55080],
       [  1281,     75,    878,  96075],
       [  1932,    369,   4317, 712908],
       ...,
       [  6300,     42,    552, 264600],
       [  7483,     45,    592, 336735],
       [  8813,     21,    276, 185073]])

In [87]:
#we can find total cost sum.
sampledata[:,2].sum()

439911

In [88]:
#we can find average of total cost.
sampledata[:,2].mean()

1466.37

In [102]:
#we create a new column called tripled units which is units * 3.
triple_units = sampledata[:,1] * 3
triple_units_col = triple_units.reshape(300,1)

In [104]:
#we add it to newdata
dataset = np.concatenate((newdata, triple_units_col), axis=1)

In [117]:
#now we save all back to the file.
np.savetxt('C:\\Users\Acer\Downloads\practice data.txt', dataset, fmt='%.f', delimiter=',          ', comments='', header='AMOUNT UNITS TOTAL_COST PROFIT TRIPLE_UNITS')

In [126]:
scores = [2,45,67,33,89,40,50,3,2,45,66,32]
scores.sort(reverse=True)
scores

[89, 67, 66, 50, 45, 45, 40, 33, 32, 3, 2, 2]

In [127]:
scores

[89, 67, 66, 50, 45, 45, 40, 33, 32, 3, 2, 2]

In [129]:
marks = [2,4,100,14,6,22,12,34,23,90]

In [132]:
marks.sort(reverse=True)
marks

[100, 90, 34, 23, 22, 14, 12, 6, 4, 2]