In [2]:
from datetime import datetime, timedelta


In [7]:
today_date = datetime.now()
today_date.day

17

In [9]:
one_week = timedelta(weeks=1)
last_week = today_date-one_week
last_week.day

10

In [10]:
name = 'gigi'
name.upper()

'GIGI'

In [15]:
9//2

4

In [16]:
print('this is my hommie\nis it true?')

this is my hommie
is it true?


In [21]:
scores=[2,5,7,4,88,45,23,90]
scores.sort(reverse=True)
scores

[90, 88, 45, 23, 7, 5, 4, 2]

In [32]:
scores[2] = 'kweku'
scores

[88, 45, 'kweku', 7, 5, 4, 2, 100]

In [36]:
person = dict()
person['name'] = 'kweku'
person['address'] = 'tema'
person


{'name': 'kweku', 'address': 'tema'}

In [45]:
person.get('address', 'unkwonw')
person.keys()

dict_keys(['name'])

In [46]:
'name' in person

True

In [51]:
if 'name' in person:
    print(person['name'])
    if 'age' in person:
        print('age is in')
        if 'name' in person:
            print(person['name'])
else:
    print('hii')

    

kweku


In [56]:
i=0
while i<6:
    i=i+1
    print(i)
    if i==5:
        print('mid')
        continue
        
    

1
2
3
4
5
mid
6


In [57]:
for values in person:
    print(values)

name


In [58]:
for i in scores:
    print(i)

88
45
kweku
7
5
4
2
100


In [61]:
def say_hi():
    print('hello dear\nhow are you')
say_hi()

hello dear
how are you


In [62]:
marks = [2,3,4,5,6,7]
for x,y in zip(marks,scores):
    print(x,y)

2 88
3 45
4 kweku
5 7
6 5
7 4


In [63]:
type(marks)

list

In [65]:
import math
math.ceil(23.34)

24

In [68]:
'monoprox'.split('o')

['m', 'n', 'pr', 'x']

In [73]:
import numpy as np
mark = np.array(marks)
marks

[2, 3, 4, 5, 6, 7]

In [72]:
mark[2]

4

In [76]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
b = np.full((2,3), 6)
b

array([[6, 6, 6],
       [6, 6, 6]])

In [81]:
x = np.random.randint(2, 5, (3,4))
x

array([[2, 3, 4, 3],
       [2, 2, 2, 4],
       [2, 4, 3, 4]])

In [101]:
y = np.array([[2,4,5,6],
              [3,5,5,5],
              [5,2,2,2],])
y * x

array([[ 4, 12, 20, 18],
       [ 6, 10, 10, 20],
       [10,  8,  6,  8]])

In [108]:
y.shape

(3, 4)

In [109]:
y.reshape(2,6)

array([[2, 4, 5, 6, 3, 5],
       [5, 5, 5, 2, 2, 2]])

In [106]:
scores

[88, 45, 'kweku', 7, 5, 4, 2, 100]

In [107]:
scores[::-1]

[100, 2, 4, 5, 7, 'kweku', 45, 88]

In [114]:
path = "C:\\Users\Acer\Downloads\wooop.txt"
dataset = np.genfromtxt(path, dtype= int, delimiter=',', skip_header=1)
dataset

array([[ 50,   5, 250,  15],
       [ 15,  25, 375,  75],
       [ 17,  10, 170,  30],
       ...,
       [ 38,  19, 722,  57],
       [ 35,  13, 455,  39],
       [ 14,  10, 140,  30]])

In [129]:
dataset.sum(axis=0)

array([ 12891,   7907, 199868,  23721])

In [125]:
new_price = dataset[:,1:4:2]

In [137]:
inflated_price = new_price.sum(axis=1).reshape(500,1)
inflated_price.shape

(500, 1)

In [142]:
newdata = np.concatenate((dataset, inflated_price), axis=1)
newdata

array([[ 50,   5, 250,  15,  20],
       [ 15,  25, 375,  75, 100],
       [ 17,  10, 170,  30,  40],
       ...,
       [ 38,  19, 722,  57,  76],
       [ 35,  13, 455,  39,  52],
       [ 14,  10, 140,  30,  40]])

In [144]:
np.savetxt(path, newdata, fmt='%.0f', delimiter=',     ', header='qty price sales, 3x price, 4x price', comments='' )